insert into ChannelProvider (ChannelProviderName, BookingFeeRate) values ('Wrapsafe', 0.9233);
insert into ChannelProvider (ChannelProviderName, BookingFeeRate) values ('Transcof', 0.0609);
insert into ChannelProvider (ChannelProviderName, BookingFeeRate) values ('Viva', 0.921);
insert into ChannelProvider (ChannelProviderName, BookingFeeRate) values ('Regrant', 0.3688);
insert into ChannelProvider (ChannelProviderName, BookingFeeRate) values ('Fintone', 0.3682);
insert into ChannelProvider (ChannelProviderName, BookingFeeRate) values ('Opela', 0.0019);
insert into ChannelProvider (ChannelProviderName, BookingFeeRate) values ('Konklux', 0.4438);
insert into ChannelProvider (ChannelProviderName, BookingFeeRate) values ('Ventosanzap', 0.3513);
insert into ChannelProvider (ChannelProviderName, BookingFeeRate) values ('Aerified', 0.7171);
insert into ChannelProvider (ChannelProviderName, BookingFeeRate) values ('Prodder', 0.9137);
insert into ChannelProvider (ChannelProviderName, BookingFeeRate) values ('Bamity', 0.4861);
insert into ChannelProvider (ChannelProviderName, BookingFeeRate) values ('Solarbreeze', 0.7277);
insert into ChannelProvider (ChannelProviderName, BookingFeeRate) values ('Wrapsafe', 0.9381);
insert into ChannelProvider (ChannelProviderName, BookingFeeRate) values ('Otcom', 0.3174);
insert into ChannelProvider (ChannelProviderName, BookingFeeRate) values ('Fix San', 0.3857);
